#!/usr/bin/env bash
# Pashu-Shield voice gateway installer (Ubuntu 22.04 / 24.04, run as root).
#
# Installs Asterisk + offline TTS, renders configs from /etc/pashu-pbx/pbx.env,
# installs the AGI gateway, firewall, fail2ban and cron jobs.
#
#   1. cp pbx/pbx.env.example /etc/pashu-pbx/pbx.env && chmod 600 /etc/pashu-pbx/pbx.env
#   2. edit /etc/pashu-pbx/pbx.env (backend URL, gateway secret, carrier trunk)
#   3. bash pbx/install.sh            (from the repo root, as root)
#
# Idempotent: safe to re-run after editing pbx.env (backs up old configs).
set -euo pipefail

PBX_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${PBX_ENV_FILE:-/etc/pashu-pbx/pbx.env}"
AST_SPOOL=/var/spool/asterisk/monitor

if [ "$(id -u)" != "0" ]; then echo "run as root" >&2; exit 1; fi
if [ ! -f "$ENV_FILE" ]; then
  echo "missing $ENV_FILE - copy pbx/pbx.env.example there first" >&2; exit 1
fi
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

require() { if [ -z "${!1:-}" ]; then echo "pbx.env: $1 is required" >&2; exit 1; fi; }
require PASHU_BACKEND_URL
require PBX_WEBHOOK_SECRET
require SIP_TRUNK_HOST
require SIP_USERNAME
require SIP_PASSWORD
require CARRIER_SIP_IPS
: "${SIP_TRUNK_PORT:=5060}"
: "${PBX_DID_LAST10:=7382210251}"
: "${RTP_PORT_START:=10000}"
: "${RTP_PORT_END:=10100}"
: "${PBX_SOUNDS_DIR:=/var/lib/asterisk/sounds/pashu}"
: "${PBX_RECORDING_DIR:=$AST_SPOOL}"
: "${PBX_RECORDING_RETENTION_DAYS:=30}"
if [ "${#PBX_WEBHOOK_SECRET}" -lt 32 ]; then
  echo "PBX_WEBHOOK_SECRET must be >= 32 chars (generate with secrets.token_hex(32))" >&2; exit 1
fi
if ! [[ "$PASHU_BACKEND_URL" =~ ^https:// ]]; then
  echo "PASHU_BACKEND_URL must be https:// (gateway secret travels on every call)" >&2; exit 1
fi

echo "==> apt packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y asterisk asterisk-core-sounds-en-gsm espeak-ng python3 fail2ban ufw cron logrotate

echo "==> asterisk user + dirs"
id asterisk >/dev/null 2>&1 || useradd -r -s /usr/sbin/nologin -d /var/lib/asterisk asterisk
mkdir -p "$PBX_SOUNDS_DIR" "$PBX_RECORDING_DIR" /var/log/asterisk
chown -R asterisk:asterisk "$PBX_SOUNDS_DIR" "$PBX_RECORDING_DIR" /var/log/asterisk /var/lib/asterisk /var/spool/asterisk
chmod 600 "$ENV_FILE"

echo "==> render asterisk configs (backup in /etc/asterisk/pashu.bak.<ts>)"
BAK="/etc/asterisk/pashu.bak.$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BAK"
for f in pjsip.conf extensions.conf rtp.conf modules.conf manager.conf http.conf logger.conf; do
  [ -f "/etc/asterisk/$f" ] && cp -a "/etc/asterisk/$f" "$BAK/$f" || true
  PBX_ENV_FILE="$ENV_FILE" python3 "$PBX_DIR/render.py" "$ENV_FILE" "$PBX_DIR/asterisk/$f.template" "/etc/asterisk/$f"
done
chown -R root:asterisk /etc/asterisk
chmod 640 /etc/asterisk/pjsip.conf /etc/asterisk/extensions.conf

echo "==> install AGI gateway"
install -m 0755 "$PBX_DIR/agi/pashu_ivr.py" /var/lib/asterisk/agi-bin/pashu_ivr.py
install -m 0755 "$PBX_DIR/agi/pashu_hangup.py" /var/lib/asterisk/agi-bin/pashu_hangup.py
install -m 0755 "$PBX_DIR/agi/pbx_heartbeat.py" /usr/local/bin/pbx-heartbeat
# AGI environment (readable by asterisk only)
umask 027
{ echo "# generated by pashu install.sh - do not edit by hand"; grep -v '^\s*#' "$ENV_FILE" | grep -v '^\s*$'; } > /etc/pashu-pbx/agi.env
chown root:asterisk /etc/pashu-pbx/agi.env; chmod 640 /etc/pashu-pbx/agi.env
# Make AGI env available to asterisk-spawned AGIs via systemd drop-in
mkdir -p /etc/systemd/system/asterisk.service.d
printf '[Service]\nEnvironmentFile=/etc/pashu-pbx/agi.env\n' > /etc/systemd/system/asterisk.service.d/pashu-env.conf

echo "==> firewall (ufw)"
bash "$PBX_DIR/security/ufw-rules.sh"

echo "==> fail2ban"
cp -a "$PBX_DIR/security/fail2ban-asterisk.local" /etc/fail2ban/jail.d/asterisk-pashu.local
cp -a "$PBX_DIR/security/fail2ban-asterisk-filter.conf" /etc/fail2ban/filter.d/asterisk-pashu.conf
systemctl enable fail2ban 2>/dev/null || true
systemctl restart fail2ban || service fail2ban restart || true

echo "==> cron: heartbeat + recording retention"
CRON_TMP="$(mktemp)"
crontab -l 2>/dev/null | grep -v "pbx-heartbeat\|pashu recording retention" > "$CRON_TMP" || true
{
  echo "PBX_ENV_FILE=$ENV_FILE"
  echo "* * * * * root set -a; . $ENV_FILE; set +a; /usr/local/bin/pbx-heartbeat >> /var/log/asterisk/pbx-heartbeat.log 2>&1"
  echo "17 3 * * * root find $PBX_RECORDING_DIR -name 'pashu-*.wav' -mtime +$PBX_RECORDING_RETENTION_DAYS -delete  # pashu recording retention"
} >> "$CRON_TMP"
crontab "$CRON_TMP"; rm -f "$CRON_TMP"

echo "==> logrotate for gateway logs"
cat > /etc/logrotate.d/pashu-pbx <<EOF
/var/log/asterisk/pashu_ivr.log /var/log/asterisk/pbx-heartbeat.log {
  weekly
  rotate 8
  compress
  missingok
  notifempty
  create 640 asterisk asterisk
}
EOF

echo "==> enable + (re)start asterisk"
systemctl daemon-reload
systemctl enable asterisk
if systemctl is-active -q asterisk; then
  asterisk -rx "core reload" || systemctl restart asterisk
else
  systemctl start asterisk
fi
sleep 3
asterisk -rx "core show version" || { echo "asterisk failed to start - see journalctl -u asterisk" >&2; exit 1; }

echo "==> smoke checks (no real call yet)"
asterisk -rx "pjsip show endpoints" | head -20 || true
asterisk -rx "dialplan show pashu-inbound" | head -12 || true
set -a; . "$ENV_FILE"; set +a; /usr/local/bin/pbx-heartbeat || echo "heartbeat failed - check PASHU_BACKEND_URL/secret + backend logs"

cat <<EOF

OK. Voice gateway installed. Remaining steps (see docs/PSTN_SIP_PBX.md):
  1. Backend (Render): TELEPHONY_PROVIDER=sip + PBX_WEBHOOK_SECRET=<same secret>
  2. Backend: PBX_ALLOWED_IPS=<this host's egress IP> (recommended)
  3. Carrier: route the helpline DID to this host (${PBX_DID_LAST10}); confirm
     signalling IPs match CARRIER_SIP_IPS and vet-leg CLI policy.
  4. Real mobile test: call ${PBX_DID_LAST10}; watch
     asterisk -rvvv  +  tail -f /var/log/asterisk/pashu_ivr.log
  5. Verify: GET https://<backend>/api/ivr/health -> pbx/sip/pstn all true.
EOF
